export const UPLOAD_PRODUCT = 'UPLOAD_PRODUCT'
export const LOADING_PRODUCT = 'LOADING_PRODUCT'
export const ERROR_PRODUCT = 'ERROR_PRODUCT'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const UPDATED_PRODUCT = 'UPDATED_PRODUCT'

export const EMAIL_LOGIN = 'EMAIL_LOGIN'
export const USER_EMAIL =  "USER_EMAIL"
export const SIGN_IN =  "SIGN_IN"
export const SUCCESSFULLY_SIGNUP = "SUCCESSFULLY_SIGNUP"
export const LOADING_LOGIN = "LOADING_LOGIN"
export const ERROR_SIGNUP = "ERROR_SIGNUP"
export const SIGN_UP = "SIGN_UP"
export const AUTH_ERROR = 'AUTH_ERROR'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNOUT_USER = 'SIGNOUT_USER'
export const UID = "UID"
